const login = require("../route/login.js")
const logined = require("../route/logined.js")
const infomation = require("../route/infomation.js")
const resigter = require("../route/resigter.js")
const resigted = require("../route/resigted.js")
const deletes = require("../route/detele.js")
const updata = require("../route/updata.js")
const add = require("../route/add.js") 
const limit = require("../route/limit.js")
module.exports = function(app){
	app.get("/login",login)
	app.post("/logined",logined)
	app.get("/infomation",infomation)
	app.get("/resigter",resigter)
	app.post("/resigted",resigted)
	app.post("/delete",deletes)
	app.post("/updata",updata)
	app.get("/add",add)
	app.post("/limit",limit)
}